export const product = [
    {id: 1, name: "Стул фольсия", prise: 23432, description: "Самый крутой стул", photo: "https://img.freepik.com/premium-photo/elegant-comfortable-chair-isolated-on-white-background_93675-88215.jpg"},
    {id: 2, name: "Стул", prise: 2323, description: "Самый крутой стул", photo: "https://img.freepik.com/premium-photo/classic-wooden-chair-isolated-on-white-background-for-the-kitchen-and-living-room-interior-design_554439-46.jpg"},
    {id: 3, name: "Стул фольсия", prise: 23432, description: "Самый крутой стул", photo: "https://nordicdesign.ru/wp-content/uploads/2020/04/warmnordic-dwell-chair-light-cyan-2-300x400.jpg"},
    {id: 4, name: "Стул фольсия", prise: 23432, description: "Самый крутой стул", photo: "https://nordicdesign.ru/wp-content/uploads/2020/04/warmnordic-dwell-chair-olive-2.jpg"},
    {id: 5, name: "Стул фольсия", prise: 23432, description: "Самый крутой стул", photo: "https://nordicdesign.ru/wp-content/uploads/2020/04/warmnordic-dwell-chair-blush-2-300x400.jpg"},
    {id: 6, name: "Стул фольсия", prise: 23432, description: "Самый крутой стул", photo: "https://nordicdesign.ru/wp-content/uploads/2020/04/warmnordic-dwell-chair-blush-2-300x400.jpg"},
    {id: 7, name: "Стул фольсия", prise: 23432, description: "Самый крутой стул", photo: "https://nordicdesign.ru/wp-content/uploads/2020/04/warmnordic-dwell-chair-blush-2-300x400.jpg"},
    {id: 8, name: "Стул фольсия", prise: 23432, description: "Самый крутой стул", photo: "https://nordicdesign.ru/wp-content/uploads/2020/04/warmnordic-dwell-chair-blush-2-300x400.jpg"},
    {id: 9, name: "Стул фольсия", prise: 23432, description: "Самый крутой стул", photo: "https://nordicdesign.ru/wp-content/uploads/2020/04/warmnordic-dwell-chair-blush-2-300x400.jpg"},
    {id: 10, name: "Стул фольсия", prise: 23432, description: "Самый крутой стул", photo: "https://nordicdesign.ru/wp-content/uploads/2020/04/warmnordic-dwell-chair-blush-2-300x400.jpg"},
    {id: 11, name: "Стул фольсия", prise: 23432, description: "Самый крутой стул", photo: "https://nordicdesign.ru/wp-content/uploads/2020/04/warmnordic-dwell-chair-blush-2-300x400.jpg"},
    {id: 12, name: "Стул фольсия", prise: 23432, description: "Самый крутой стул", photo: "https://nordicdesign.ru/wp-content/uploads/2020/04/warmnordic-dwell-chair-blush-2-300x400.jpg"},
    {id: 13, name: "Стул фольсия", prise: 23432, description: "Самый крутой стул", photo: "https://nordicdesign.ru/wp-content/uploads/2020/04/warmnordic-dwell-chair-blush-2-300x400.jpg"},
    {id: 14, name: "Стул фольсия", prise: 23432, description: "Самый крутой стул", photo: "https://nordicdesign.ru/wp-content/uploads/2020/04/warmnordic-dwell-chair-blush-2-300x400.jpg"},
    {id: 15, name: "Стул фольсия", prise: 23432, description: "Самый крутой стул", photo: "https://nordicdesign.ru/wp-content/uploads/2020/04/warmnordic-dwell-chair-blush-2-300x400.jpg"},
    {id: 16, name: "Стул фольсия", prise: 23432, description: "Самый крутой стул", photo: "https://nordicdesign.ru/wp-content/uploads/2020/04/warmnordic-dwell-chair-blush-2-300x400.jpg"},
    {id: 17, name: "Стул фольсия", prise: 23432, description: "Самый крутой стул", photo: "https://nordicdesign.ru/wp-content/uploads/2020/04/warmnordic-dwell-chair-blush-2-300x400.jpg"},
]