version: '3.5'

services:
  db_styliaOnline:
    container_name: db_styliaOnline
    ports:
      - "5438:5432"
    restart: always
    environment:
      - POSTGRES_DB=db_styliaOnline
      - POSTGRES_PASSWORD=i5fz%4Nz&o*b#1Ep
      - POSTGRES_USER=root
    image: postgres:15.2-alpine